# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_calc.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 318)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.historyTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.historyTextEdit.setObjectName("historyTextEdit")
        self.verticalLayout.addWidget(self.historyTextEdit)
        self.expressionLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.expressionLineEdit.setObjectName("expressionLineEdit")
        self.verticalLayout.addWidget(self.expressionLineEdit)
        self.firstButttonHorizLayout = QtWidgets.QHBoxLayout()
        self.firstButttonHorizLayout.setObjectName("firstButttonHorizLayout")
        self.button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_7.setObjectName("button_7")
        self.firstButttonHorizLayout.addWidget(self.button_7)
        self.button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_8.setObjectName("button_8")
        self.firstButttonHorizLayout.addWidget(self.button_8)
        self.button_9 = QtWidgets.QPushButton(self.centralwidget)
        self.button_9.setObjectName("button_9")
        self.firstButttonHorizLayout.addWidget(self.button_9)
        self.button_divide = QtWidgets.QPushButton(self.centralwidget)
        self.button_divide.setObjectName("button_divide")
        self.firstButttonHorizLayout.addWidget(self.button_divide)
        self.verticalLayout.addLayout(self.firstButttonHorizLayout)
        self.secondButttonHorizLayout = QtWidgets.QHBoxLayout()
        self.secondButttonHorizLayout.setObjectName("secondButttonHorizLayout")
        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4.setObjectName("button_4")
        self.secondButttonHorizLayout.addWidget(self.button_4)
        self.button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5.setObjectName("button_5")
        self.secondButttonHorizLayout.addWidget(self.button_5)
        self.button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6.setObjectName("button_6")
        self.secondButttonHorizLayout.addWidget(self.button_6)
        self.button_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.button_multiply.setObjectName("button_multiply")
        self.secondButttonHorizLayout.addWidget(self.button_multiply)
        self.verticalLayout.addLayout(self.secondButttonHorizLayout)
        self.thirdButttonHorizLayout = QtWidgets.QHBoxLayout()
        self.thirdButttonHorizLayout.setObjectName("thirdButttonHorizLayout")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setObjectName("button_1")
        self.thirdButttonHorizLayout.addWidget(self.button_1)
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setObjectName("button_2")
        self.thirdButttonHorizLayout.addWidget(self.button_2)
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setObjectName("button_3")
        self.thirdButttonHorizLayout.addWidget(self.button_3)
        self.button_minus = QtWidgets.QPushButton(self.centralwidget)
        self.button_minus.setObjectName("button_minus")
        self.thirdButttonHorizLayout.addWidget(self.button_minus)
        self.verticalLayout.addLayout(self.thirdButttonHorizLayout)
        self.fourthButttonHorizLayout = QtWidgets.QHBoxLayout()
        self.fourthButttonHorizLayout.setObjectName("fourthButttonHorizLayout")
        self.button_0 = QtWidgets.QPushButton(self.centralwidget)
        self.button_0.setObjectName("button_0")
        self.fourthButttonHorizLayout.addWidget(self.button_0)
        self.button_float_point = QtWidgets.QPushButton(self.centralwidget)
        self.button_float_point.setObjectName("button_float_point")
        self.fourthButttonHorizLayout.addWidget(self.button_float_point)
        self.button_equals = QtWidgets.QPushButton(self.centralwidget)
        self.button_equals.setObjectName("button_equals")
        self.fourthButttonHorizLayout.addWidget(self.button_equals)
        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus.setObjectName("button_plus")
        self.fourthButttonHorizLayout.addWidget(self.button_plus)
        self.verticalLayout.addLayout(self.fourthButttonHorizLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_divide.setText(_translate("MainWindow", "/"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_multiply.setText(_translate("MainWindow", "*"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_float_point.setText(_translate("MainWindow", ","))
        self.button_equals.setText(_translate("MainWindow", "="))
        self.button_plus.setText(_translate("MainWindow", "+"))

