# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_calc.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(653, 318)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.historyTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.historyTextEdit.setReadOnly(True)
        self.historyTextEdit.setObjectName("historyTextEdit")
        self.verticalLayout.addWidget(self.historyTextEdit)
        self.expressionLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.expressionLineEdit.setObjectName("expressionLineEdit")
        self.verticalLayout.addWidget(self.expressionLineEdit)
        self.firstButttonHorizLayout = QtWidgets.QHBoxLayout()
        self.firstButttonHorizLayout.setObjectName("firstButttonHorizLayout")
        self.button_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_7.sizePolicy().hasHeightForWidth())
        self.button_7.setSizePolicy(sizePolicy)
        self.button_7.setMinimumSize(QtCore.QSize(85, 27))
        self.button_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_7.setObjectName("button_7")
        self.firstButttonHorizLayout.addWidget(self.button_7)
        self.button_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_8.sizePolicy().hasHeightForWidth())
        self.button_8.setSizePolicy(sizePolicy)
        self.button_8.setMinimumSize(QtCore.QSize(85, 27))
        self.button_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_8.setObjectName("button_8")
        self.firstButttonHorizLayout.addWidget(self.button_8)
        self.button_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_9.sizePolicy().hasHeightForWidth())
        self.button_9.setSizePolicy(sizePolicy)
        self.button_9.setMinimumSize(QtCore.QSize(85, 27))
        self.button_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_9.setObjectName("button_9")
        self.firstButttonHorizLayout.addWidget(self.button_9)
        self.button_divide = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_divide.sizePolicy().hasHeightForWidth())
        self.button_divide.setSizePolicy(sizePolicy)
        self.button_divide.setMinimumSize(QtCore.QSize(85, 27))
        self.button_divide.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_divide.setObjectName("button_divide")
        self.firstButttonHorizLayout.addWidget(self.button_divide)
        self.button_sin = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_sin.sizePolicy().hasHeightForWidth())
        self.button_sin.setSizePolicy(sizePolicy)
        self.button_sin.setMinimumSize(QtCore.QSize(85, 27))
        self.button_sin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_sin.setObjectName("button_sin")
        self.firstButttonHorizLayout.addWidget(self.button_sin)
        self.button_asin = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_asin.sizePolicy().hasHeightForWidth())
        self.button_asin.setSizePolicy(sizePolicy)
        self.button_asin.setMinimumSize(QtCore.QSize(85, 27))
        self.button_asin.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_asin.setObjectName("button_asin")
        self.firstButttonHorizLayout.addWidget(self.button_asin)
        self.button_back = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_back.sizePolicy().hasHeightForWidth())
        self.button_back.setSizePolicy(sizePolicy)
        self.button_back.setMinimumSize(QtCore.QSize(85, 27))
        self.button_back.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_back.setObjectName("button_back")
        self.firstButttonHorizLayout.addWidget(self.button_back)
        self.verticalLayout.addLayout(self.firstButttonHorizLayout)
        self.secondButttonHorizLayout = QtWidgets.QHBoxLayout()
        self.secondButttonHorizLayout.setObjectName("secondButttonHorizLayout")
        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_4.sizePolicy().hasHeightForWidth())
        self.button_4.setSizePolicy(sizePolicy)
        self.button_4.setMinimumSize(QtCore.QSize(85, 27))
        self.button_4.setObjectName("button_4")
        self.secondButttonHorizLayout.addWidget(self.button_4)
        self.button_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_5.sizePolicy().hasHeightForWidth())
        self.button_5.setSizePolicy(sizePolicy)
        self.button_5.setMinimumSize(QtCore.QSize(85, 27))
        self.button_5.setObjectName("button_5")
        self.secondButttonHorizLayout.addWidget(self.button_5)
        self.button_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_6.sizePolicy().hasHeightForWidth())
        self.button_6.setSizePolicy(sizePolicy)
        self.button_6.setMinimumSize(QtCore.QSize(85, 27))
        self.button_6.setObjectName("button_6")
        self.secondButttonHorizLayout.addWidget(self.button_6)
        self.button_multiply = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_multiply.sizePolicy().hasHeightForWidth())
        self.button_multiply.setSizePolicy(sizePolicy)
        self.button_multiply.setMinimumSize(QtCore.QSize(85, 27))
        self.button_multiply.setObjectName("button_multiply")
        self.secondButttonHorizLayout.addWidget(self.button_multiply)
        self.button_cos = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_cos.sizePolicy().hasHeightForWidth())
        self.button_cos.setSizePolicy(sizePolicy)
        self.button_cos.setMinimumSize(QtCore.QSize(85, 27))
        self.button_cos.setObjectName("button_cos")
        self.secondButttonHorizLayout.addWidget(self.button_cos)
        self.button_acos = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_acos.sizePolicy().hasHeightForWidth())
        self.button_acos.setSizePolicy(sizePolicy)
        self.button_acos.setMinimumSize(QtCore.QSize(85, 27))
        self.button_acos.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_acos.setObjectName("button_acos")
        self.secondButttonHorizLayout.addWidget(self.button_acos)
        self.button_clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clear.sizePolicy().hasHeightForWidth())
        self.button_clear.setSizePolicy(sizePolicy)
        self.button_clear.setMinimumSize(QtCore.QSize(85, 27))
        self.button_clear.setObjectName("button_clear")
        self.secondButttonHorizLayout.addWidget(self.button_clear)
        self.verticalLayout.addLayout(self.secondButttonHorizLayout)
        self.thirdButttonHorizLayout = QtWidgets.QHBoxLayout()
        self.thirdButttonHorizLayout.setObjectName("thirdButttonHorizLayout")
        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_1.sizePolicy().hasHeightForWidth())
        self.button_1.setSizePolicy(sizePolicy)
        self.button_1.setMinimumSize(QtCore.QSize(85, 27))
        self.button_1.setObjectName("button_1")
        self.thirdButttonHorizLayout.addWidget(self.button_1)
        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_2.sizePolicy().hasHeightForWidth())
        self.button_2.setSizePolicy(sizePolicy)
        self.button_2.setMinimumSize(QtCore.QSize(85, 27))
        self.button_2.setObjectName("button_2")
        self.thirdButttonHorizLayout.addWidget(self.button_2)
        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_3.sizePolicy().hasHeightForWidth())
        self.button_3.setSizePolicy(sizePolicy)
        self.button_3.setMinimumSize(QtCore.QSize(85, 27))
        self.button_3.setObjectName("button_3")
        self.thirdButttonHorizLayout.addWidget(self.button_3)
        self.button_minus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_minus.sizePolicy().hasHeightForWidth())
        self.button_minus.setSizePolicy(sizePolicy)
        self.button_minus.setMinimumSize(QtCore.QSize(85, 27))
        self.button_minus.setObjectName("button_minus")
        self.thirdButttonHorizLayout.addWidget(self.button_minus)
        self.button_left_parentheses = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_left_parentheses.sizePolicy().hasHeightForWidth())
        self.button_left_parentheses.setSizePolicy(sizePolicy)
        self.button_left_parentheses.setMinimumSize(QtCore.QSize(85, 27))
        self.button_left_parentheses.setObjectName("button_left_parentheses")
        self.thirdButttonHorizLayout.addWidget(self.button_left_parentheses)
        self.button_tan = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_tan.sizePolicy().hasHeightForWidth())
        self.button_tan.setSizePolicy(sizePolicy)
        self.button_tan.setMinimumSize(QtCore.QSize(85, 27))
        self.button_tan.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_tan.setObjectName("button_tan")
        self.thirdButttonHorizLayout.addWidget(self.button_tan)
        self.button_clear_hist = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_clear_hist.sizePolicy().hasHeightForWidth())
        self.button_clear_hist.setSizePolicy(sizePolicy)
        self.button_clear_hist.setMinimumSize(QtCore.QSize(85, 27))
        self.button_clear_hist.setObjectName("button_clear_hist")
        self.thirdButttonHorizLayout.addWidget(self.button_clear_hist)
        self.verticalLayout.addLayout(self.thirdButttonHorizLayout)
        self.fourthButttonHorizLayout = QtWidgets.QHBoxLayout()
        self.fourthButttonHorizLayout.setObjectName("fourthButttonHorizLayout")
        self.button_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_0.sizePolicy().hasHeightForWidth())
        self.button_0.setSizePolicy(sizePolicy)
        self.button_0.setMinimumSize(QtCore.QSize(85, 27))
        self.button_0.setObjectName("button_0")
        self.fourthButttonHorizLayout.addWidget(self.button_0)
        self.button_float_point = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_float_point.sizePolicy().hasHeightForWidth())
        self.button_float_point.setSizePolicy(sizePolicy)
        self.button_float_point.setMinimumSize(QtCore.QSize(85, 27))
        self.button_float_point.setObjectName("button_float_point")
        self.fourthButttonHorizLayout.addWidget(self.button_float_point)
        self.button_equals = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_equals.sizePolicy().hasHeightForWidth())
        self.button_equals.setSizePolicy(sizePolicy)
        self.button_equals.setMinimumSize(QtCore.QSize(85, 27))
        self.button_equals.setObjectName("button_equals")
        self.fourthButttonHorizLayout.addWidget(self.button_equals)
        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_plus.sizePolicy().hasHeightForWidth())
        self.button_plus.setSizePolicy(sizePolicy)
        self.button_plus.setMinimumSize(QtCore.QSize(85, 27))
        self.button_plus.setObjectName("button_plus")
        self.fourthButttonHorizLayout.addWidget(self.button_plus)
        self.button_right_parentheses = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_right_parentheses.sizePolicy().hasHeightForWidth())
        self.button_right_parentheses.setSizePolicy(sizePolicy)
        self.button_right_parentheses.setMinimumSize(QtCore.QSize(85, 27))
        self.button_right_parentheses.setObjectName("button_right_parentheses")
        self.fourthButttonHorizLayout.addWidget(self.button_right_parentheses)
        self.button_atan = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_atan.sizePolicy().hasHeightForWidth())
        self.button_atan.setSizePolicy(sizePolicy)
        self.button_atan.setMinimumSize(QtCore.QSize(85, 27))
        self.button_atan.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.button_atan.setObjectName("button_atan")
        self.fourthButttonHorizLayout.addWidget(self.button_atan)
        self.button_pi = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_pi.sizePolicy().hasHeightForWidth())
        self.button_pi.setSizePolicy(sizePolicy)
        self.button_pi.setMinimumSize(QtCore.QSize(85, 27))
        self.button_pi.setObjectName("button_pi")
        self.fourthButttonHorizLayout.addWidget(self.button_pi)
        self.verticalLayout.addLayout(self.fourthButttonHorizLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 653, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_7.setShortcut(_translate("MainWindow", "7"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_8.setShortcut(_translate("MainWindow", "8"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_9.setShortcut(_translate("MainWindow", "9"))
        self.button_divide.setText(_translate("MainWindow", "/"))
        self.button_divide.setShortcut(_translate("MainWindow", "/"))
        self.button_sin.setStatusTip(_translate("MainWindow", "Please don\'t forget about parentheses"))
        self.button_sin.setWhatsThis(_translate("MainWindow", "trigonometric function"))
        self.button_sin.setText(_translate("MainWindow", "sin"))
        self.button_asin.setStatusTip(_translate("MainWindow", "Please don\'t forget about parentheses"))
        self.button_asin.setWhatsThis(_translate("MainWindow", "trigonometric function"))
        self.button_asin.setText(_translate("MainWindow", "asin"))
        self.button_back.setText(_translate("MainWindow", "back"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_4.setShortcut(_translate("MainWindow", "4"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_5.setShortcut(_translate("MainWindow", "5"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_6.setShortcut(_translate("MainWindow", "6"))
        self.button_multiply.setText(_translate("MainWindow", "*"))
        self.button_multiply.setShortcut(_translate("MainWindow", "*"))
        self.button_cos.setStatusTip(_translate("MainWindow", "Please don\'t forget about parentheses"))
        self.button_cos.setWhatsThis(_translate("MainWindow", "trigonometric function"))
        self.button_cos.setText(_translate("MainWindow", "cos"))
        self.button_acos.setStatusTip(_translate("MainWindow", "Please don\'t forget about parentheses"))
        self.button_acos.setWhatsThis(_translate("MainWindow", "trigonometric function"))
        self.button_acos.setText(_translate("MainWindow", "acos"))
        self.button_clear.setText(_translate("MainWindow", "clear"))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_1.setShortcut(_translate("MainWindow", "1"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_2.setShortcut(_translate("MainWindow", "2"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_3.setShortcut(_translate("MainWindow", "3"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_minus.setShortcut(_translate("MainWindow", "-"))
        self.button_left_parentheses.setText(_translate("MainWindow", "("))
        self.button_left_parentheses.setShortcut(_translate("MainWindow", "("))
        self.button_tan.setStatusTip(_translate("MainWindow", "Please don\'t forget about parentheses"))
        self.button_tan.setWhatsThis(_translate("MainWindow", "trigonometric function"))
        self.button_tan.setText(_translate("MainWindow", "tan"))
        self.button_clear_hist.setText(_translate("MainWindow", "clear hist"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_0.setShortcut(_translate("MainWindow", "0"))
        self.button_float_point.setText(_translate("MainWindow", "."))
        self.button_float_point.setShortcut(_translate("MainWindow", "."))
        self.button_equals.setText(_translate("MainWindow", "="))
        self.button_equals.setShortcut(_translate("MainWindow", "Return"))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_plus.setShortcut(_translate("MainWindow", "+"))
        self.button_right_parentheses.setText(_translate("MainWindow", ")"))
        self.button_right_parentheses.setShortcut(_translate("MainWindow", ")"))
        self.button_atan.setStatusTip(_translate("MainWindow", "Please don\'t forget about parentheses"))
        self.button_atan.setWhatsThis(_translate("MainWindow", "trigonometric function"))
        self.button_atan.setText(_translate("MainWindow", "atan"))
        self.button_pi.setText(_translate("MainWindow", "pi"))

